#!/bin/bash

[ -n "$1" ] && [ "$1" = "-h" ] && ( echo "usage: $0 [duration]"; exit 0 )

echo -en "recording ${1:-10} seconds of sound:"
arecord -d ${1:-10} /tmp/mic-test.wav
echo " done"
sleep 1
echo -en "playing recording:"
aplay -D hw:1,0 /tmp/mic-test.wav
echo " done"
